using DucAnhERP.SeedWork;
using System.ComponentModel.DataAnnotations;

namespace DucAnhERP.ViewModel
{
    public class HopRanhThangModel: PagingParameters
    {
        [Key]
        public string Id { get; set; }
        public string ThongTinLyTrinh_TuyenDuong { get; set; }
        public string ThongTinLyTrinh_LyTrinhTaiTimHoGa { get; set; }
        public string ThongTinChungHoGa_TenHoGaSauPhanLoai { get; set; }
        public string ThongTinChungHoGa_TenHoGaTheoBanVe { get; set; }
        public string ThongTinChungHoGa_HinhThucHoGa { get; set; }
        public string ThongTinChungHoGa_KetCauMuMo { get; set; }
        public string ThongTinChungHoGa_KetCauTuong { get; set; }
        public string ThongTinChungHoGa_HinhThucMongHoGa { get; set; }
        public string ThongTinChungHoGa_KetCauMong { get; set; }
        public string ThongTinChungHoGa_ChatMatTrong { get; set; }
        public string ThongTinChungHoGa_ChatMatNgoai { get; set; }
        public Double PhuBiHoGa_CDai { get; set; }
        public Double PhuBiHoGa_CRong { get; set; }
        public Double BeTongLotMong_D { get; set; }
        public Double BeTongLotMong_R { get; set; }
        public Double BeTongLotMong_C { get; set; }
        public Double BeTongMongHoGa_D { get; set; }
        public Double BeTongMongHoGa_R { get; set; }
        public Double TBeTongMongHoGa_C { get; set; }
        public Double DeHoGa_D { get; set; }
        public Double DeHoGa_R { get; set; }
        public Double DeHoGa_C { get; set; }
        public Double TuongHoGa_D { get; set; }
        public Double TuongHoGa_R { get; set; }
        public Double TuongHoGa_CdTuong { get; set; }
        public Double DamGiuaHoGa_D { get; set; }
        public Double DamGiuaHoGa_R { get; set; }
        public Double DamGiuaHoGa_C { get; set; }
        public Double DamGiuaHoGa_CdDam { get; set; }
        public Double DamGiuaHoGa_CCaoDamGiuaTuongSoVoiDayHoGa { get; set; }
        public Double ChatMatTrong_D { get; set; }
        public Double ChatMatTrong_R { get; set; }
        public Double ChatMatNgoaiCanh_D { get; set; }
        public Double ChatMatNgoaiCanh_R { get; set; }
        public Double MuMoThotDuoi_D { get; set; }
        public Double MuMoThotDuoi_R { get; set; }
        public Double MuMoThotDuoi_C { get; set; }
        public Double MuMoThotDuoi_CdTuong { get; set; }
        public Double MuMoThotTren_D { get; set; }
        public Double MuMoThotTren_R { get; set; }
        public Double MuMoThotTren_C { get; set; }
        public Double MuMoThotTren_CdTuong { get; set; }
        public Double HinhThucDauNoi1_Loai { get; set; }
        public Double HinhThucDauNoi1_CanhDai { get; set; }
        public Double HinhThucDauNoi1_CanhRong { get; set; }
        public Double HinhThucDauNoi1_CanhCheo { get; set; }
        public Double HinhThucDauNoi2_Loai { get; set; }
        public Double HinhThucDauNoi2_CanhDai { get; set; }
        public Double HinhThucDauNoi2_CanhRong { get; set; }
        public Double HinhThucDauNoi2_CanhCheo { get; set; }
        public Double HinhThucDauNoi3_Loai { get; set; }
        public Double HinhThucDauNoi3_CanhDai { get; set; }
        public Double HinhThucDauNoi3_CanhRong { get; set; }
        public Double HinhThucDauNoi3_CanhCheo { get; set; }
        public Double HinhThucDauNoi4_Loai { get; set; }
        public Double HinhThucDauNoi4_CanhDai { get; set; }
        public Double HinhThucDauNoi4_CanhRong { get; set; }
        public Double HinhThucDauNoi4_CanhCheo { get; set; }
        public Double HinhThucDauNoi5_Loai { get; set; }
        public Double HinhThucDauNoi5_CanhDai { get; set; }
        public Double HinhThucDauNoi5_CanhRong { get; set; }
        public Double HinhThucDauNoi5_CanhCheo { get; set; }
        public Double HinhThucDauNoi6_Loai { get; set; }
        public Double HinhThucDauNoi6_CanhDai { get; set; }
        public Double HinhThucDauNoi6_CanhRong { get; set; }
        public Double HinhThucDauNoi6_CanhCheo { get; set; }
        public Double HinhThucDauNoi7_Loai { get; set; }
        public Double HinhThucDauNoi7_CanhDai { get; set; }
        public Double HinhThucDauNoi7_CanhRong { get; set; }
        public Double HinhThucDauNoi7_CanhCheo { get; set; }
        public Double HinhThucDauNoi8_Loai { get; set; }
        public Double HinhThucDauNoi8_CanhDai { get; set; }
        public Double HinhThucDauNoi8_CanhRong { get; set; }
        public Double HinhThucDauNoi8_CanhCheo { get; set; }
        public string ThongTinTamDanHoGa2_PhanLoaiDayHoGa { get; set; }
        public string ThongTinTamDanHoGa2_HinhThucDayHoGa { get; set; }
        public Double ThongTinTamDanHoGa2_DuongKinh { get; set; }
        public Double ThongTinTamDanHoGa2_ChieuDay { get; set; }
        public Double ThongTinTamDanHoGa2_D { get; set; }
        public Double ThongTinTamDanHoGa2_R { get; set; }
        public Double ThongTinTamDanHoGa2_C { get; set; }
        public int ThongTinTamDanHoGa2_SoLuongNapDay { get; set; }
        public string ThongTinVatLieuDaoHoGa_LoaiVatLieuDao { get; set; }
        public Double ThongTinVatLieuDaoHoGa_ChieuCaoDaoDa { get; set; }
        public Double ThongTinCaoDoHoGa_CaoDoTuNhien { get; set; }
        public Double ThongTinCaoDoHoGa_CdDinhViaHeHoanThien { get; set; }
        public Double ThongTinCaoDoHoGa_CaoDoDinhK98 { get; set; }
        public Double ThongTinCaoDoHoGa_CdDayHoGa { get; set; }
        public Double ThongTinCaoDoHoGa_CdDinhHoGa { get; set; }
        public Double ThongTinMaiDao_ChieuRongDayDaoNho { get; set; }
        public Double ThongTinMaiDao_TyLeMoMai { get; set; }
        public int ThongTinMaiDao_SoCanhMaiTrai { get; set; }
        public int ThongTinMaiDao_SoCanhMaiPhai { get; set; }
        public Double ToaDoX { get; set; }
        public Double ToaDoY { get; set; }
        public Double ThongTinLyTrinhTruyenDan_TuLyTrinh { get; set; }
        public Double ThongTinLyTrinhTruyenDan_DenLyTrinh { get; set; }
        public string ThongTinLyTrinhTruyenDan_TuHoGa { get; set; }
        public string ThongTinLyTrinhTruyenDan_DenHoGa { get; set; }
        public string ThongTinDuongTruyenDan_HinhThucTruyenDan { get; set; }
        public string ThongTinDuongTruyenDan_LoaiTruyenDan { get; set; }
        public string ThongTinDuongTruyenDan_TenLoaiTruyenDanSauPhanLoai { get; set; }
        public Double TTCDSLCauKienDuongTruyenDan_ChieuDai01CauKien { get; set; }
        public Double TTCDSLCauKienDuongTruyenDan_ChieuDaiMoiNoiCKien { get; set; }
        public int TTCDSLCauKienDuongTruyenDan_SoLuongCKienDungDeTinhChieuDaiBoSung { get; set; }
        public Double TTCDSLCauKienDuongTruyenDan_TongChieuDai { get; set; }
        public string ThongTinMongDuongTruyenDan_PhanLoaiMongCongTronCongHop { get; set; }
        public string ThongTinMongDuongTruyenDan_LoaiMong { get; set; }
        public string ThongTinMongDuongTruyenDan_HinhThucMong { get; set; }
        public string ThongTinDeCong_TenLoaiDeCong { get; set; }
        public string ThongTinDeCong_CauTaoDeCong { get; set; }
        public Double ThongTinDeCong_D { get; set; }
        public Double ThongTinDeCong_R { get; set; }
        public Double ThongTinDeCong_C { get; set; }
        public Double ThongTinDeCong_SlDeCong01CauKienTruyenDan { get; set; }
        public Double ThongTinDeCong_Kl01DeCong { get; set; }
        public Double ThongTinCauTaoCongTron_CDayPhuBi { get; set; }
        public Double ThongTinCauTaoCongTron_SoCanh { get; set; }
        public Double ThongTinCauTaoCongTron_LongSuDung { get; set; }
        public Double ThongTinCauTaoCongTron_CCaoLotMong { get; set; }
        public Double ThongTinCauTaoCongTron_CRongLotMong { get; set; }
        public Double ThongTinCauTaoCongTron_CCaoMong { get; set; }
        public Double ThongTinCauTaoCongTron_CRongMong { get; set; }
        public Double ThongTinCauTaoCongTron_CCaoDe { get; set; }
        public string TTKTHHCongHopRanh_CauTaoTuong { get; set; }
        public string TTKTHHCongHopRanh_CauTaoMuMo { get; set; }
        public string TTKTHHCongHopRanh_ChatMatTrong { get; set; }
        public string TTKTHHCongHopRanh_ChatMatNgoai { get; set; }
        public Double TTKTHHCongHopRanh_CCaoLotMong { get; set; }
        public Double TTKTHHCongHopRanh_CRongLotMong { get; set; }
        public Double TTKTHHCongHopRanh_CCaoMong { get; set; }
        public Double TTKTHHCongHopRanh_CRongMong { get; set; }
        public Double TTKTHHCongHopRanh_CCaoDe { get; set; }
        public Double TTKTHHCongHopRanh_CRongDe { get; set; }
        public Double TTKTHHCongHopRanh_CDayTuong01Ben { get; set; }
        public Double TTKTHHCongHopRanh_SoLuongTuong { get; set; }
        public Double TTKTHHCongHopRanh_CRongLongSuDung { get; set; }
        public Double TTKTHHCongHopRanh_CCaoTuongCongHop { get; set; }
        public Double TTKTHHCongHopRanh_CCaoMuMoThotDuoi { get; set; }
        public Double TTKTHHCongHopRanh_CRongMuMoDuoi { get; set; }
        public Double TTKTHHCongHopRanh_CCaoMuMoThotTren { get; set; }
        public Double TTKTHHCongHopRanh_CRongMuMoTren { get; set; }
        public string TTKTHHCongHopRanh_LoaiThanhChong { get; set; }
        public string TTKTHHCongHopRanh_CauTaoThanhChong { get; set; }
        public Double TTKTHHCongHopRanh_CCaoThanhChong { get; set; }
        public Double TTKTHHCongHopRanh_CRongThanhChong { get; set; }
        public Double TTKTHHCongHopRanh_CDai { get; set; }
        public Double TTKTHHCongHopRanh_SoLuongThanhChong { get; set; }
        public Double ThongTinKichThuocHinhHocOngNhua_CDayPhuBi { get; set; }
        public int ThongTinKichThuocHinhHocOngNhua_SoCanh { get; set; }
        public Double ThongTinKichThuocHinhHocOngNhua_LongSuDung { get; set; }
        public Double ThongTinKichThuocHinhHocOngNhua_CCaoDemCat { get; set; }
        public Double ThongTinKichThuocHinhHocOngNhua_CCaoDapCat { get; set; }
        public string ThongTinRanhThang_HinhThucMai { get; set; }
        public string ThongTinRanhThang_CauTaoChanKhay { get; set; }
        public string ThongTinRanhThang_CauTaoGiangDinh { get; set; }
        public string ThongTinRanhThang_HinhThucHanhLangBaoVe { get; set; }
        public string ThongTinRanhThang_PhanLoaiChanKhay { get; set; }
        public Double ThongTinRanhThang_CCaoLotChanKhay { get; set; }
        public Double ThongTinRanhThang_CRongLotChanKhay { get; set; }
        public Double ThongTinRanhThang_SoLuongLotChanKhay { get; set; }
        public Double ThongTinRanhThang_CCaoMongChanKhay { get; set; }
        public Double ThongTinRanhThang_CRongMongChanKhay { get; set; }
        public int ThongTinRanhThang_SoLuongMongChanKhay { get; set; }
        public Double ThongTinRanhThang_CCaoLot { get; set; }
        public Double ThongTinRanhThang_CRongLot { get; set; }
        public Double ThongTinRanhThang_CCaoMong { get; set; }
        public Double ThongTinRanhThang_CRongMong { get; set; }
        public string ThongTinRanhThang_PhanLoaiMai { get; set; }
        public double ThongTinRanhThang_CRongMai { get; set; }
        public double ThongTinRanhThang_CDayMai { get; set; }
        public int ThongTinRanhThang_SoLuongMai { get; set; }
        public string ThongTinRanhThang_PhanLoaiGiangDinh { get; set; }
        public Double ThongTinRanhThang_CCaoLotGiangDinh { get; set; }
        public Double ThongTinRanhThang_CRongLotGiangDinh { get; set; }
        public int ThongTinRanhThang_SoLuongLotGiangDinh { get; set; }
        public Double ThongTinRanhThang_CCaoMongGiangDinh { get; set; }
        public Double ThongTinRanhThang_CRongMongGiangDinh { get; set; }
        public Double ThongTinRanhThang_SoLuongMongGiangDinh { get; set; }
        public string ThongTinRanhThang_PhanLoaiHanhLangBaoVe { get; set; }
        public Double ThongTinRanhThang_CCaoHanhLangBaoVe { get; set; }
        public Double ThongTinRanhThang_CRongHanhLangBaoVe { get; set; }
        public int ThongTinRanhThang_SoLuongHangLangBaoVe { get; set; }
        public string TTTDCongHoRanh_TenLoaiTamDanTieuChuan { get; set; }
        public string TTTDCongHoRanh_CauTaoTamDanTruyenDanTamDanTieuChuan { get; set; }
        public Double TTTDCongHoRanh_CDai { get; set; }
        public Double TTTDCongHoRanh_CRong { get; set; }
        public Double TTTDCongHoRanh_CCao { get; set; }
        public string TTTDCongHoRanh_TenLoaiTamDanLoai02 { get; set; }
        public string TTTDCongHoRanh_CauTaoTamDanTruyenDan { get; set; }
        public Double TTTDCongHoRanh_CRong1 { get; set; }
        public Double TTTDCongHoRanh_CCao1 { get; set; }
        public Double TTTDCongHoRanh_ChieuDaiMoiNoi { get; set; }
        public int TTTDCongHoRanh_SoLuongTDanDungDeTinhChieuDaiBoSung { get; set; }
        public Double CDThuongLuu_HienTrangTruocKhiDaoThuongLuu { get; set; }
        public Double CDThuongLuu_DayDongChay { get; set; }
        public Double CDThuongLuu_DinhTrongLongSuDung { get; set; }
        public Double CDThuongLuu_ChieuCaoRanhThangTuDayDongChayDenDinh { get; set; }
        public Double CDHaLu_HienTrangTruocKhiDaoHaLuu { get; set; }
        public Double CDHaLu_DayDongChay { get; set; }
        public Double CDHaLu_DinhTrongLongSuDung { get; set; }
        public Double CDHaLu_ChieuCaoRanhThangTuDayDongChayDenDinh { get; set; }
        public Double TTMDRanhOngThang_ChieuRongDayDaoNho { get; set; }
        public Double TTMDRanhOngThang_TyLeMoMai { get; set; }
        public int TTMDRanhOngThang_SoCanhMaiTrai { get; set; }
        public Double TTMDRanhOngThang_SoCanhMaiPhai { get; set; }
        public Double TTMDRanhOngThang_ChieuRongDayDaoNho1 { get; set; }
        public Double TTMDRanhOngThang_TyLeMoMai1 { get; set; }
        public int TTMDRanhOngThang_SoCanhMaiTrai1 { get; set; }
        public Double TTMDRanhOngThang_SoCanhMaiPhai1 { get; set; }
        public Double TuToaDoX { get; set; }
        public Double TuToaDoY { get; set; }
        public Double DenToaDoX { get; set; }
        public Double DenToaDoY { get; set; }
        public DateTime CreateAt { get; set; }
    }
}
