using DucAnhERP.SeedWork;
using System.ComponentModel.DataAnnotations;

namespace DucAnhERP.ViewModel.NghiepVuCongTrinh
{
    public class NuocMuaModel : PagingParameters
    {
        [Key]
        public string Id { get; set; } = Guid.NewGuid().ToString();
        public string ThongTinLyTrinh_TuyenDuong { get; set; }
        public string ThongTinLyTrinh_LyTrinhTaiTimHoGa { get; set; }
        public string ThongTinChungHoGa_TenHoGaSauPhanLoai { get; set; }
        public string PhanLoaiHoGas_TenHoGaSauPhanLoai { get; set; } 
        public string ThongTinChungHoGa_TenHoGaTheoBanVe { get; set; }
        public string ThongTinChungHoGa_HinhThucHoGa { get; set; }
        public string ThongTinChungHoGa_HinhThucHoGa_Name { get; set; }
        public string ThongTinChungHoGa_KetCauMuMo { get; set; }
        public string ThongTinChungHoGa_KetCauMuMo_Name { get; set; }
        public string ThongTinChungHoGa_KetCauTuong { get; set; }
        public string ThongTinChungHoGa_KetCauTuong_Name { get; set; }
        public string ThongTinChungHoGa_HinhThucMongHoGa { get; set; }
        public string ThongTinChungHoGa_HinhThucMongHoGa_Name { get; set; }
        public string ThongTinChungHoGa_KetCauMong { get; set; }
        public string ThongTinChungHoGa_KetCauMong_Name { get; set; }
        public string ThongTinChungHoGa_ChatMatTrong { get; set; }
        public string ThongTinChungHoGa_ChatMatTrong_Name { get; set; }
        public string ThongTinChungHoGa_ChatMatNgoai { get; set; }
        public string ThongTinChungHoGa_ChatMatNgoai_Name { get; set; }
        public double PhuBiHoGa_CDai { get; set; }
        public double PhuBiHoGa_CRong { get; set; }
        public double BeTongLotMong_D { get; set; }
        public double BeTongLotMong_R { get; set; }
        public double BeTongLotMong_C { get; set; }
        public double BeTongMongHoGa_D { get; set; }
        public double BeTongMongHoGa_R { get; set; }
        public double BeTongMongHoGa_C { get; set; }
        public double DeHoGa_D { get; set; }
        public double DeHoGa_R { get; set; }
        public double DeHoGa_C { get; set; }
        public double TuongHoGa_D { get; set; }
        public double TuongHoGa_R { get; set; }
        public double TuongHoGa_C { get; set; }
        public double TuongHoGa_CdTuong { get; set; }
        public double DamGiuaHoGa_D { get; set; }
        public double DamGiuaHoGa_R { get; set; }
        public double DamGiuaHoGa_C { get; set; }
        public double DamGiuaHoGa_CdDam { get; set; }
        public double DamGiuaHoGa_CCaoDamGiuaTuongSoVoiDayHoGa { get; set; }
        public double ChatMatTrong_D { get; set; }
        public double ChatMatTrong_R { get; set; }
        public double ChatMatTrong_C { get; set; }
        public double ChatMatNgoaiCanh_D { get; set; }
        public double ChatMatNgoaiCanh_R { get; set; }
        public double ChatMatNgoaiCanh_C { get; set; }
        public double MuMoThotDuoi_D { get; set; }
        public double MuMoThotDuoi_R { get; set; }
        public double MuMoThotDuoi_C { get; set; }
        public double MuMoThotDuoi_CdTuong { get; set; }
        public double MuMoThotTren_D { get; set; }
        public double MuMoThotTren_R { get; set; }
        public double MuMoThotTren_C { get; set; }
        public double MuMoThotTren_CdTuong { get; set; }
        public double HinhThucDauNoi1_Loai { get; set; }
        public string HinhThucDauNoi1_KLBoSung { get; set; }
        public string HinhThucDauNoi1_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi1_CanhDai { get; set; }
        public double HinhThucDauNoi1_CDD { get; set; }
        public double HinhThucDauNoi1_CDR { get; set; }
        public double HinhThucDauNoi1_CDC { get; set; }
        public double HinhThucDauNoi1_CanhRong { get; set; }
        public double HinhThucDauNoi1_CRD { get; set; }
        public double HinhThucDauNoi1_CRR { get; set; }
        public double HinhThucDauNoi1_CRC { get; set; }
        public double HinhThucDauNoi1_CanhCheo { get; set; }
        public double HinhThucDauNoi1_CCD { get; set; }
        public double HinhThucDauNoi1_CCR { get; set; }
        public double HinhThucDauNoi1_CCC { get; set; }
        public double HinhThucDauNoi2_Loai { get; set; }
        public string HinhThucDauNoi2_KLBoSung { get; set; }
        public string HinhThucDauNoi2_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi2_CanhDai { get; set; }
        public double HinhThucDauNoi2_CDD { get; set; }
        public double HinhThucDauNoi2_CDR { get; set; }
        public double HinhThucDauNoi2_CDC { get; set; }
        public double HinhThucDauNoi2_CanhRong { get; set; }
        public double HinhThucDauNoi2_CRD { get; set; }
        public double HinhThucDauNoi2_CRR { get; set; }
        public double HinhThucDauNoi2_CRC { get; set; }
        public double HinhThucDauNoi2_CanhCheo { get; set; }
        public double HinhThucDauNoi2_CCD { get; set; }
        public double HinhThucDauNoi2_CCR { get; set; }
        public double HinhThucDauNoi2_CCC { get; set; }
        public double HinhThucDauNoi3_Loai { get; set; }
        public string HinhThucDauNoi3_KLBoSung { get; set; }
        public string HinhThucDauNoi3_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi3_CanhDai { get; set; }
        public double HinhThucDauNoi3_CDD { get; set; }
        public double HinhThucDauNoi3_CDR { get; set; }
        public double HinhThucDauNoi3_CDC { get; set; }
        public double HinhThucDauNoi3_CanhRong { get; set; }
        public double HinhThucDauNoi3_CRD { get; set; }
        public double HinhThucDauNoi3_CRR { get; set; }
        public double HinhThucDauNoi3_CRC { get; set; }
        public double HinhThucDauNoi3_CanhCheo { get; set; }
        public double HinhThucDauNoi3_CCD { get; set; }
        public double HinhThucDauNoi3_CCR { get; set; }
        public double HinhThucDauNoi3_CCC { get; set; }
        public double HinhThucDauNoi4_Loai { get; set; }
        public string HinhThucDauNoi4_KLBoSung { get; set; }
        public string HinhThucDauNoi4_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi4_CanhDai { get; set; }
        public double HinhThucDauNoi4_CDD { get; set; }
        public double HinhThucDauNoi4_CDR { get; set; }
        public double HinhThucDauNoi4_CDC { get; set; }
        public double HinhThucDauNoi4_CanhRong { get; set; }

        public double HinhThucDauNoi4_CRD { get; set; }
        public double HinhThucDauNoi4_CRR { get; set; }
        public double HinhThucDauNoi4_CRC { get; set; }
        public double HinhThucDauNoi4_CanhCheo { get; set; }
        public double HinhThucDauNoi4_CCD { get; set; }
        public double HinhThucDauNoi4_CCR { get; set; }
        public double HinhThucDauNoi4_CCC { get; set; }
        public double HinhThucDauNoi5_Loai { get; set; }
        public string HinhThucDauNoi5_KLBoSung { get; set; }
        public string HinhThucDauNoi5_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi5_CanhDai { get; set; }
        public double HinhThucDauNoi5_CDD { get; set; }
        public double HinhThucDauNoi5_CDR { get; set; }
        public double HinhThucDauNoi5_CDC { get; set; }
        public double HinhThucDauNoi5_CanhRong { get; set; }
        public double HinhThucDauNoi5_CRD { get; set; }
        public double HinhThucDauNoi5_CRR { get; set; }
        public double HinhThucDauNoi5_CRC { get; set; }
        public double HinhThucDauNoi5_CanhCheo { get; set; }
        public double HinhThucDauNoi5_CCD { get; set; }
        public double HinhThucDauNoi5_CCR { get; set; }
        public double HinhThucDauNoi5_CCC { get; set; }
        public double HinhThucDauNoi6_Loai { get; set; }
        public string HinhThucDauNoi6_KLBoSung { get; set; }
        public string HinhThucDauNoi6_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi6_CanhDai { get; set; }
        public double HinhThucDauNoi6_CDD { get; set; }
        public double HinhThucDauNoi6_CDR { get; set; }
        public double HinhThucDauNoi6_CDC { get; set; }
        public double HinhThucDauNoi6_CanhRong { get; set; }
        public double HinhThucDauNoi6_CRD { get; set; }
        public double HinhThucDauNoi6_CRR { get; set; }
        public double HinhThucDauNoi6_CRC { get; set; }
        public double HinhThucDauNoi6_CanhCheo { get; set; }
        public double HinhThucDauNoi6_CCD { get; set; }
        public double HinhThucDauNoi6_CCR { get; set; }
        public double HinhThucDauNoi6_CCC { get; set; }
        public double HinhThucDauNoi7_Loai { get; set; }
        public string HinhThucDauNoi7_KLBoSung { get; set; }
        public string HinhThucDauNoi7_KLBoSung_Name { get; set; }
        public double HinhThucDauNoi7_CanhDai { get; set; }
        public double HinhThucDauNoi7_CDD { get; set; }
        public double HinhThucDauNoi7_CDR { get; set; }
        public double HinhThucDauNoi7_CDC { get; set; }
        public double HinhThucDauNoi7_CanhRong { get; set; }
        public double HinhThucDauNoi7_CRD { get; set; }
        public double HinhThucDauNoi7_CRR { get; set; }
        public double HinhThucDauNoi7_CRC { get; set; }
        public double HinhThucDauNoi7_CanhCheo { get; set; }
        public double HinhThucDauNoi7_CCD { get; set; }
        public double HinhThucDauNoi7_CCR { get; set; }
        public double HinhThucDauNoi7_CCC { get; set; }
        public double HinhThucDauNoi8_Loai { get; set; }
        public string HinhThucDauNoi8_KLBoSung {get;set;}
        public string HinhThucDauNoi8_KLBoSung_Name {get;set;}
        public double HinhThucDauNoi8_CanhDai { get; set; }
        public double HinhThucDauNoi8_CDD { get; set; }
        public double HinhThucDauNoi8_CDR { get; set; }
        public double HinhThucDauNoi8_CDC { get; set; }
        public double HinhThucDauNoi8_CanhRong { get; set; }
        public double HinhThucDauNoi8_CRD { get; set; }
        public double HinhThucDauNoi8_CRR { get; set; }
        public double HinhThucDauNoi8_CRC { get; set; }
        public double HinhThucDauNoi8_CanhCheo { get; set; }
        public double HinhThucDauNoi8_CCD { get; set; }
        public double HinhThucDauNoi8_CCR { get; set; }
        public double HinhThucDauNoi8_CCC { get; set; }
        public string ThongTinTamDanHoGa2_PhanLoaiDayHoGa { get; set; }
        public string PhanLoaiTDHoGa_PhanLoaiDayHoGa { get; set; }
        public string ThongTinTamDanHoGa2_HinhThucDayHoGa { get; set; }
        public string ThongTinTamDanHoGa2_HinhThucDayHoGa_Name { get; set; }
        public double ThongTinTamDanHoGa2_DuongKinh { get; set; }
        public double ThongTinTamDanHoGa2_ChieuDay { get; set; }
        public double ThongTinTamDanHoGa2_D { get; set; }
        public double ThongTinTamDanHoGa2_R { get; set; }
        public double ThongTinTamDanHoGa2_C { get; set; }
        public double ThongTinTamDanHoGa2_SoLuongNapDay { get; set; }
        public string ThongTinVatLieuDaoHoGa_LoaiVatLieuDao { get; set; }
        public string ThongTinVatLieuDaoHoGa_LoaiVatLieuDao_Name { get; set; }
        public double ThongTinVatLieuDaoHoGa_ChieuCaoDaoDa { get; set; }
        public double ThongTinVatLieuDaoHoGa_ChieuCaoDaoDat { get; set; }
        public double ThongTinVatLieuDaoHoGa_TongChieuCaoDao { get; set; }
        public double ThongTinCaoDoHoGa_CaoDoTuNhien { get; set; }
        public double ThongTinCaoDoHoGa_CdDinhViaHeHoanThien { get; set; }
        public double ThongTinCaoDoHoGa_CaoDoDinhK98 { get; set; }
        public double ThongTinCaoDoHoGa_CaoDoHienTrangTruocKhiDao { get; set; }
        public double ThongTinCaoDoHoGa_DayDao { get; set; }
        public double ThongTinCaoDoHoGa_CSauDao { get; set; }
        public double ThongTinCaoDoHoGa_DinhLotMong { get; set; }
        public double ThongTinCaoDoHoGa_CdDinhMong { get; set; }
        public double ThongTinCaoDoHoGa_CdDayHoGa { get; set; }
        public double ThongTinCaoDoHoGa_CCaoTuong { get; set; }
        public double ThongTinCaoDoHoGa_DinhTuongDuoiDamGiuaTuong { get; set; }
        public double ThongTinCaoDoHoGa_DinhDamGiuaTuong { get; set; }
        public double ThongTinCaoDoHoGa_DinhTuong { get; set; }
        public double ThongTinCaoDoHoGa_DinhMuMoThotDuoi { get; set; }
        public double ThongTinCaoDoHoGa_CdDinhHoGa { get; set; }
        public double ThongTinCaoDoHoGa_TongChieuCaoHoGa { get; set; }
        public double ThongTinCaoDoHoGa_ChenhCaoDinhHoGaVaHienTrangDao { get; set; }
        public double ThongTinCaoDoHoGa_TongChieuCaoChiemChoDapTra { get; set; }
        public double TTCCCCDTHT_ChieuCaoLotDat { get; set; }
        public double TTCCCCDTHT_ChieuCaoMongDat { get; set; }
        public double TTCCCCDTHT_ChieuCaoTuongDat { get; set; }
        public double TTCCCCDTHT_ChieuCaoLotDa { get; set; }
        public double TTCCCCDTHT_ChieuCaoMongDa { get; set; }
        public double TTCCCCDTHT_ChieuCaoTuongDa { get; set; }
        public double TTCCCCDTHT_TongCieuCaoDat { get; set; }
        public double TTCCCCDTHT_TongChieuCaoDa { get; set; }
        public double TTCCCCDTHT_ChenhDatSoVoiTK { get; set; }
        public double TTCCCCDTHT_ChenhDaSoVoiTK { get; set; }
        public double ThongTinMaiDao_ChieuRongDayDaoNho { get; set; }
        public double ThongTinMaiDao_TyLeMoMai { get; set; }
        public double ThongTinMaiDao_SoCanhMaiTrai { get; set; }
        public double ThongTinMaiDao_SoCanhMaiPhai { get; set; }
        public double TTKLD_CRongDaoDayLonDat { get; set; }
        public double TTKLD_CRongDaoDayLonDa { get; set; }
        public double TTKLD_DienTichDaoDat { get; set; }
        public double TTKLD_DienTichDaoDa { get; set; }
        public double TTKLD_TongDtDao { get; set; }
        public double TTKLD_KlDaoDat { get; set; }
        public double TTKLD_KlDaoDa { get; set; }
        public double TTKLD_TongKlDao { get; set; }
        public double TTKLD_KlChiemChoDat { get; set; }
        public double TTKLD_KlChiemChoDa { get; set; }
        public double TTKLD_TongChiemCho { get; set; }
        public double TTKLD_KlDapTraDat { get; set; }
        public double TTKLD_KlDapTraDa { get; set; }
        public double TTKLD_TongDapTra { get; set; }
        public double TTKLD_KlThuaDat { get; set; }
        public double TTKLD_KlThuaDa { get; set; }
        public double TTKLD_TongThua { get; set; }
        public double ThongTinLyTrinhTruyenDan_TuLyTrinh { get; set; }
        public double ThongTinLyTrinhTruyenDan_DenLyTrinh { get; set; }
        public string ThongTinLyTrinhTruyenDan_TuHoGa { get; set; }
        public string ThongTinLyTrinhTruyenDan_DenHoGa { get; set; }
        public string ThongTinDuongTruyenDan_HinhThucTruyenDan { get; set; }
        public string ThongTinDuongTruyenDan_HinhThucTruyenDan_Name { get; set; }
        public string ThongTinDuongTruyenDan_LoaiTruyenDan { get; set; }
        public string ThongTinDuongTruyenDan_LoaiTruyenDan_Name { get; set; }
        public string ThongTinDuongTruyenDan_TenLoaiTruyenDanSauPhanLoai { get; set; }
        public string PhanLoaiCTronHopNhua_TenLoaiTruyenDanSauPhanLoai { get; set; }

        public double TTCDSLCauKienDuongTruyenDan_TongChieuDai { get; set; }
        public double TTCDSLCauKienDuongTruyenDan_ChieuDai01CauKien { get; set; }
        public double TTCDSLCauKienDuongTruyenDan_SlCauKienTinhKl { get; set; }

        public string ThongTinMongDuongTruyenDan_PhanLoaiMongCongTronCongHop { get; set; }
        public string PhanLoaiMongCTron_PhanLoaiMongCongTronCongHop { get; set; }
        public string ThongTinMongDuongTruyenDan_LoaiMong { get; set; }
        public string ThongTinMongDuongTruyenDan_LoaiMong_Name { get; set; }
        public string ThongTinMongDuongTruyenDan_HinhThucMong { get; set; }
        public string ThongTinMongDuongTruyenDan_HinhThucMong_Name { get; set; }

        public string ThongTinDeCong_TenLoaiDeCong { get; set; }
        public string PhanLoaiDeCong_TenLoaiDeCong { get; set; }
        public string ThongTinDeCong_CauTaoDeCong { get; set; }
        public string ThongTinDeCong_CauTaoDeCong_Name { get; set; }
        public double ThongTinDeCong_D { get; set; }
        public double ThongTinDeCong_R { get; set; }
        public double ThongTinDeCong_C { get; set; }
        public double ThongTinDeCong_SlDeCong01CauKienTruyenDan { get; set; }
        public double ThongTinDeCong_Kl01DeCong { get; set; }
        public double ThongTinDeCong_TongSoLuongDC { get; set; }
        public double ThongTinDeCong_TongKLDeCong { get; set; }
        public double ThongTinCauTaoCongTron_CDayPhuBi { get; set; }
        public double ThongTinCauTaoCongTron_SoCanh { get; set; }
        public double ThongTinCauTaoCongTron_LongSuDung { get; set; }
        public double ThongTinCauTaoCongTron_CCaoCauKien { get; set; }
        public double ThongTinCauTaoCongTron_CCaoLotMong { get; set; }
        public double ThongTinCauTaoCongTron_CRongLotMong { get; set; }
        public double ThongTinCauTaoCongTron_CCaoMong { get; set; }
        public double ThongTinCauTaoCongTron_CRongMong { get; set; }
        public double ThongTinCauTaoCongTron_CCaoDe { get; set; }
        public double ThongTinCauTaoCongTron_TongCCaoCong { get; set; }
        public double TTTKLCKCTCH_CDMoiNoiCKien { get; set; }
        public double TTTKLCKCTCH_SLCKDungDeTinhCD { get; set; }
        public double TTTKLCKCTCH_SLCKNguyen { get; set; }
        public double TTTKLCKCTCH_CDCanLapDat { get; set; }
        public double TTTKLCKCTCH_TongCD { get; set; }
        public double TTTKLCKCTCH_CDThucTeThuaThieu { get; set; }
        public string TTTKLCKCTCH_XDOngCongCanThem { get; set; }
        public double TTTKLCKCTCH_CDThuaThieuSauTinhKL { get; set; }

        public string TTKTHHCongHopRanh_CauTaoTuong { get; set; }
        public string TTKTHHCongHopRanh_CauTaoTuong_Name { get; set; }
        public string TTKTHHCongHopRanh_CauTaoMuMo { get; set; }
        public string TTKTHHCongHopRanh_CauTaoMuMo_Name { get; set; }
        public string TTKTHHCongHopRanh_ChatMatTrong { get; set; }
        public string TTKTHHCongHopRanh_ChatMatTrong_Name { get; set; }
        public string TTKTHHCongHopRanh_ChatMatNgoai { get; set; }
        public string TTKTHHCongHopRanh_ChatMatNgoai_Name { get; set; }

        public double TTKTHHCongHopRanh_CCaoLotMong { get; set; }
        public double TTKTHHCongHopRanh_CRongLotMong { get; set; }
        public double TTKTHHCongHopRanh_CCaoMong { get; set; }
        public double TTKTHHCongHopRanh_CRongMong { get; set; }
        public double TTKTHHCongHopRanh_CCaoDe { get; set; }
        public double TTKTHHCongHopRanh_CRongDe { get; set; }
        public double TTKTHHCongHopRanh_CDayTuong01Ben { get; set; }
        public double TTKTHHCongHopRanh_SoLuongTuong { get; set; }
        public double TTKTHHCongHopRanh_CRongLongSuDung { get; set; }
        public double TTKTHHCongHopRanh_CCaoTuongCongHop { get; set; }
        public double TTKTHHCongHopRanh_CCaoTuongRanh { get; set; }
        public double TTKTHHCongHopRanh_CCaoTuongGop { get; set; }
        public double TTKTHHCongHopRanh_CCaoMuMoThotDuoi { get; set; }
        public double TTKTHHCongHopRanh_CRongMuMoDuoi { get; set; }
        public double TTKTHHCongHopRanh_CCaoMuMoThotTren { get; set; }
        public double TTKTHHCongHopRanh_CRongMuMoTren { get; set; }
        public string TTKTHHCongHopRanh_LoaiThanhChong { get; set; }
        public string PhanLoaiThanhChong_LoaiThanhChong { get; set; }
        public string TTKTHHCongHopRanh_CauTaoThanhChong { get; set; }
        public string TTKTHHCongHopRanh_CauTaoThanhChong_Name { get; set; }
        public double TTKTHHCongHopRanh_CCaoThanhChong { get; set; }
        public double TTKTHHCongHopRanh_CRongThanhChong { get; set; }
        public double TTKTHHCongHopRanh_CDai { get; set; }
        public double TTKTHHCongHopRanh_SoLuongThanhChong { get; set; }
        public double TTKTHHCongHopRanh_CCaoChatMatTrong { get; set; }
        public double TTKTHHCongHopRanh_CCaoChatmatNgoai { get; set; }
        public double TTKTHHCongHopRanh_TongChieuCao { get; set; }
        public string TTTDCongHoRanh_TenLoaiTamDanTieuChuan { get; set; }
        public string PhanLoaiTDanTDan_TenLoaiTamDanTieuChuan { get; set; }
        public string TTTDCongHoRanh_CauTaoTamDanTruyenDanTamDanTieuChuan { get; set; }
        public string TTTDCongHoRanh_CauTaoTamDanTruyenDanTamDanTieuChuan_Name { get; set; }
        public double TTTDCongHoRanh_SoLuong { get; set; }
        public double TTTDCongHoRanh_CDai { get; set; }
        public double TTTDCongHoRanh_CRong { get; set; }
        public double TTTDCongHoRanh_CCao { get; set; }
        public string TTTDCongHoRanh_TenLoaiTamDanLoai02 { get; set; }
        public string PhanLoaiTDanTDan_TenLoaiTamDanLoai02 { get; set; }
        public string TTTDCongHoRanh_CauTaoTamDanTruyenDan { get; set; }
        public string TTTDCongHoRanh_CauTaoTamDanTruyenDan_Name { get; set; }
        public double TTTDCongHoRanh_SoLuong1 { get; set; }
        public double TTTDCongHoRanh_CDai1 { get; set; }
        public double TTTDCongHoRanh_CRong1 { get; set; }
        public double TTTDCongHoRanh_CCao1 { get; set; }
        public double TTTDCongHoRanh_ChieuDaiMoiNoi { get; set; }
        public double TTTDCongHoRanh_SoLuongTDanDungDeTinhChieuDaiBoSung { get; set; }
        public double TTTDCongHoRanh_SLCauKienNguyen { get; set; }
        public double TTTDCongHoRanh_ChieuDaiTheoSoCKNguyen { get; set; }
        public double TTTDCongHoRanh_TongChieuDaiTheoCKNguyen { get; set; }
        public double TTTDCongHoRanh_ChieuDaiThucTe { get; set; }
        public string TTTDCongHoRanh_XacDinhOngCongCanThem { get; set; }
        public double ThongTinKichThuocHinhHocOngNhua_CDayPhuBi { get; set; }
        public double ThongTinKichThuocHinhHocOngNhua_SoCanh { get; set; }
        public double ThongTinKichThuocHinhHocOngNhua_LongSuDung { get; set; }
        public double ThongTinKichThuocHinhHocOngNhua_TongCCaoOng { get; set; }
        public double ThongTinKichThuocHinhHocOngNhua_CCaoDemCat { get; set; }
        public double ThongTinKichThuocHinhHocOngNhua_CCaoDapCat { get; set; }
        public double CDThuongLuu_HienTrangTruocKhiDaoThuongLuu { get; set; }
        public double CDThuongLuu_DayDaoGop { get; set; }
        public double CDThuongLuu_ChieuSauDao { get; set; }
        public double CDThuongLuu_DayDaoCongTron { get; set; }
        public double CDThuongLuu_DayDaoCongHop { get; set; }
        public double CDThuongLuu_DayDaoRanh { get; set; }
        public double CDThuongLuu_DayDaoOngNhua { get; set; }
        public double CDThuongLuu_DinhLotGop { get; set; }
        public double CDThuongLuu_DinhLotOngNhua { get; set; }
        public double CDThuongLuu_DinhLotCongTron { get; set; }
        public double CDThuongLuu_DinhLotCongHop { get; set; }
        public double CDThuongLuu_DinhLotRanh { get; set; }
        public double CDThuongLuu_DinhMongGop { get; set; }
        public double CDThuongLuu_DinhMongCongTron { get; set; }
        public double CDThuongLuu_DinhMongCongHop { get; set; }
        public double CDThuongLuu_DinhMongRanh { get; set; }
        public double CDThuongLuu_DinhDeCong { get; set; }
        public double CDThuongLuu_DayDongChay { get; set; }
        public double CDThuongLuu_CCaoTuongCongRanh { get; set; }
        public double CDThuongLuu_DinhTuongCHopRanh { get; set; }
        public double CDThuongLuu_DinhMuMoThotDuoiCongHopRanh { get; set; }
        public double CDThuongLuu_DinhGop { get; set; }
        public double CDThuongLuu_DinhTrongLongSuDung { get; set; }
        public double CDThuongLuu_DinhCongTron { get; set; }
        public double CDThuongLuu_DinhCongHop { get; set; }
        public double CDThuongLuu_DinhRanh { get; set; }
        public double CDThuongLuu_DinhOngNhua { get; set; }
        public double CDThuongLuu_DinhDapCat { get; set; }
        public double CDHaLu_HienTrangTruocKhiDaoHaLuu { get; set; }
        public double CDHaLu_DayDaoGop { get; set; }
        public double CDHaLu_ChieuSauDao { get; set; }
        public double CDHaLu_DayDaoCongTron { get; set; }
        public double CDHaLu_DayDaoCongHop { get; set; }
        public double CDHaLu_DayDaoRanh { get; set; }
        public double CDHaLu_DayDaoOngNhua { get; set; }
        public double CDHaLu_DinhLotGop { get; set; }
        public double CDHaLu_DinhLotOngNhua { get; set; }
        public double CDHaLu_DinhLotCongTron { get; set; }
        public double CDHaLu_DinhLotCongHop { get; set; }
        public double CDHaLu_DinhLotRanh { get; set; }
        public double CDHaLu_DinhMongGop { get; set; }
        public double CDHaLu_DinhMongCongTron { get; set; }
        public double CDHaLu_DinhMongCongHop { get; set; }
        public double CDHaLu_DinhMongRanh { get; set; }
        public double CDHaLu_DinhDeCong { get; set; }
        public double CDHaLu_DayDongChay { get; set; }
        public double CDHaLu_CCaoTuongCongRanh { get; set; }
        public double CDHaLu_DinhTuongCHopRanh { get; set; }
        public double CDHaLu_DinhMuMoThotDuoiCongHopRanh { get; set; }
        public double CDHaLu_DinhGop { get; set; }
        public double CDHaLu_DinhTrongLongSuDung { get; set; }
        public double CDHaLu_DinhCongTron { get; set; }
        public double CDHaLu_DinhCongHop { get; set; }
        public double CDHaLu_DinhRanh { get; set; }
        public double CDHaLu_DinhOngNhua { get; set; }
        public double CDHaLu_DinhDapCat { get; set; }
        public string TTVLDCongRanh_LoaiVatLieuDao { get; set; }
        public string TTVLDCongRanh_LoaiVatLieuDao_Name { get; set; }
        public double TTVLDCongRanh_TLChieuCaoDaoDa { get; set; }
        public double TTVLDCongRanh_TLChieuCaoDaoDat { get; set; }
        public double TTVLDCongRanh_TLTongChieuSauDao { get; set; }
        public double TTVLDCongRanh_HLChieuCaoDaoDa { get; set; }
        public double TTVLDCongRanh_HLChieuCaoDaoDat { get; set; }
        public double TTVLDCongRanh_HLTongChieuSauDao { get; set; }
        public double TTCCCCT_CCaoLotDatTLuu { get; set; }
        public double TTCCCCT_CCaoLotDatHLuu { get; set; }
        public double TTCCCCT_CCaoLotDatMongTBinh { get; set; }
        public double TTCCCCT_CCaoLotDaTLuu { get; set; }
        public double TTCCCCT_CCaoLotDaHLuu { get; set; }
        public double TTCCCCT_CCaoLotDaMongTBinh { get; set; }
        public double TTCCCCT_CCaoMongDatTLuu { get; set; }
        public double TTCCCCT_CCaoMongDatHLuu { get; set; }
        public double TTCCCCT_CCaoMongDatTBinh { get; set; }
        public double TTCCCCT_CCaoMongDaTLuu { get; set; }
        public double TTCCCCT_CCaoMongDaHLuu { get; set; }
        public double TTCCCCT_CCaoMongDaTBinh { get; set; }
        public double TTCCCCT_CCaoDeDatTLuu { get; set; }
        public double TTCCCCT_CCaoDeDatHLuu { get; set; }
        public double TTCCCCT_CCaoDeDatTBinh { get; set; }
        public double TTCCCCT_CCaoDeDaTLuu { get; set; }
        public double TTCCCCT_CCaoDeDaHLuu { get; set; }
        public double TTCCCCT_CCaoDeDaTBinh { get; set; }
        public double TTCCCCT_CCaoCongDatTLuu { get; set; }
        public double TTCCCCT_CCaoCongDatHLuu { get; set; }
        public double TTCCCCT_CCongCongDatTBinh { get; set; }
        public double TTCCCCT_CCaoCongDaTLuu { get; set; }
        public double TTCCCCT_CCaoCongDaHLuu { get; set; }
        public double TTCCCCT_CCongCongDaTBinh { get; set; }
        public double TTCCCCCHR_CCaoLotDatTLuu { get; set; }
        public double TTCCCCCHR_CCaoLotDatHLuu { get; set; }
        public double TTCCCCCHR_CCaoLotDatTBinh { get; set; }
        public double TTCCCCCHR_CCaoLotDaTLuu { get; set; }
        public double TTCCCCCHR_CCaoLotDaHLuu { get; set; }
        public double TTCCCCCHR_CCaoLotDaTBinh { get; set; }
        public double TTCCCCCHR_CCaoMongDatTLuu { get; set; }
        public double TTCCCCCHR_CCaoMongDatHLuu { get; set; }
        public double TTCCCCCHR_CCaoMongDatTBinh { get; set; }
        public double TTCCCCCHR_CCaoMongDaTLuu { get; set; }
        public double TTCCCCCHR_CCaoMongDaHLuu { get; set; }
        public double TTCCCCCHR_CCaoMongDaTBinh { get; set; }
        public double TTCCCCCHR_CCaoTuongDatTLuu { get; set; }
        public double TTCCCCCHR_CCaoTuongDatHLuu { get; set; }
        public double TTCCCCCHR_CCaoTuongDatTBinh { get; set; }
        public double TTCCCCCHR_CCaoTuongDaTLuu { get; set; }
        public double TTCCCCCHR_CCaoTuongDaHLuu { get; set; }
        public double TTCCCCCHR_CCaoTuongDaTBinh { get; set; }
        public double TTCCCCON_CCaoDemCatDatTLuu { get; set; }
        public double TTCCCCON_CCaoDemCatDatHLuu { get; set; }
        public double TTCCCCON_CCaoDemCatDatTBinh { get; set; }
        public double TTCCCCON_CCaoDemCatDaTLuu { get; set; }
        public double TTCCCCON_CCaoDemCatDaHLuu { get; set; }
        public double TTCCCCON_CCaoDemCatDaTBinh { get; set; }
        public double TTCCCCON_CCaoOngDatTLuu { get; set; }
        public double TTCCCCON_CCaoOngDatHLuu { get; set; }
        public double TTCCCCON_CCaoDatTBinh { get; set; }
        public double TTCCCCON_CCaoOngDaTLuu { get; set; }
        public double TTCCCCON_CCaoOngDaHLuu { get; set; }
        public double TTCCCCON_CCaoDaTBinh { get; set; }
        public double TTCCCCON_CCaoDapCatDatTLuu { get; set; }
        public double TTCCCCON_CCaoDapCatDatHLuu { get; set; }
        public double TTCCCCON_CCaoDapCatDatTBinh { get; set; }
        public double TTCCCCON_CCaoDapCatDaTLuu { get; set; }
        public double TTCCCCON_CCaoDapCatDaHLuu { get; set; }
        public double TTCCCCON_CCaoDapCatDaTBinh { get; set; }
        public double TTMDRanhOngThang_ChieuRongDayDaoNho { get; set; }
        public double TTMDRanhOngThang_TyLeMoMai { get; set; }
        public double TTMDRanhOngThang_SoCanhMaiTrai { get; set; }
        public double TTMDRanhOngThang_SoCanhMaiPhai { get; set; }
        public double DTDTLCRONRT_CRongDaoDatDayLon { get; set; }
        public double DTDTLCRONRT_DTichDaoDat { get; set; }
        public double DTDTLCRONRT_CRongDaoDaDayLon { get; set; }
        public double DTDTLCRONRT_DTichDaoDa { get; set; }
        public double DTDHLCRONRT_CRongDaoDatDayLon { get; set; }
        public double DTDHLCRONRT_DTichDaoDat { get; set; }
        public double DTDHLCRONRT_CRongDaoDaDayLon { get; set; }
        public double DTDHLCRONRT_DTichDaoDa { get; set; }
        public double DTDTB_DaoDatCRDaoDayLon { get; set; }
        public double DTDTB_DaoDatDTDao { get; set; }
        public double DTDTB_DaoDaCRDaoDayLon { get; set; }
        public double DTDTB_DaoDaDTDao { get; set; }
        public double TKLD_KlDaoDat { get; set; }
        public double TKLD_KlDaoDa { get; set; }
        public double TKLD_TongKlDaoCongRanhOngNhuaRanhThang { get; set; }
        public double TKLD_KlCChoDatCongTron { get; set; }
        public double TKLD_KlCChoDaCongTron { get; set; }
        public double TKLD_TongKlChiemChoCTron { get; set; }
        public double TKLD_KlCChoDatCongHop { get; set; }
        public double TKLD_KlCChoDaCongHop { get; set; }
        public double TKLD_TongKlCChoCongHop { get; set; }
        public double TKLD_KlCChoDatRanh { get; set; }
        public double TKLD_KlCChoDaRanh { get; set; }
        public double TKLD_TongKlCChoRanh { get; set; }
        public double TKLD_KlCChoDatOngNhua { get; set; }
        public double TKLD_KlCChoDaOngNhua { get; set; }
        public double TKLD_TongKlCChoOngNhua { get; set; }
        public double TKLD_KlCChoDat { get; set; }
        public double TKLD_KlCChoDa { get; set; }
        public double TKLD_TongChiemCho { get; set; }
        public double TKLD_KlDapTraDat { get; set; }
        public double TKLD_KlDapTraDa { get; set; }
        public double TKLD_TongKlDapTra { get; set; }
        public double TKLD_KlThuaDat { get; set; }
        public double TKLD_KlThuaDa { get; set; }
        public double TKLD_TongKLThua { get; set; }
        public double DTDC_TLCSauDap { get; set; }
        public double DTDC_TLCRongDapDayLon { get; set; }
        public double DTDC_TLDTichDap { get; set; }
        public double DTDC_HLCSauDap { get; set; }
        public double DTDC_HLCRongDapDayLon { get; set; }
        public double DTDC_HLDTichDap { get; set; }
        public double DTTB_CSDap { get; set; }
        public double DTTB_CRDapDayLon { get; set; }
        public double DTTB_DTichDap { get; set; }
        public double TTKLDC_KlDapCatTruocChiemCho { get; set; }
        public double TTKLDC_KlChiemCho { get; set; }
        public double TTKLDC_KlDapCatSauChiemCho { get; set; }
        public double ToaDoX { get; set; }
        public double ToaDoY { get; set; }

        // TraiPhai 0= Trái , 1= phải , 2 all
        public int? TraiPhai { get; set; } = 2;
        public int Flag { get; set; } = 0;
        public DateTime? CreateAt { get; set; }
        public string? CreateBy { get; set; }
        public int? IsActive { get; set; }

    }
}
